Apply formatter to all the codes in the repo #51 (#52)
Changelog
====
- Improves .github/workflows/check_diff_format.yml to run pylint, yapf
and apply mypy to the files only changed
- Improves bin/command/check-diff-format to use yapf and advance the
logging message in the code related to shfmt
- Introduces mypy.ini to avoid unnecessary warning messages
- Adds .mypy_cache to .gitignore to ignore the change in mypy cache
files
- Applys formatter to all the codes in the repo

diff --git a/bin/command/check-diff-format b/bin/command/check-diff-format
--- a/bin/command/check-diff-format
+++ b/bin/command/check-diff-format
@@ -14,13 +14,25 @@ PYTHON_FILES=$(echo "$CHANGED_FILES" | grep '\.py$')
 
 # Check the shell scripts using shfmt
 for file in $SHELL_FILES; do
-    echo "Checking $file..."
+    echo "Checking $file with shfmt..."
     shfmt -d -i 4 "$file"
     if [ $? -ne 0 ]; then # $? retrieves the exit code of the last command
         echo "Error in $file!"
         exit 1
     else
-        echo "Succeed!"
+        echo -e "Succeed!\n"
+    fi
+done
+
+# Check the python files using yapf
+for file in $PYTHON_FILES; do
+    echo "Checking $file with yapf..."
+    yapf -dr "$file"
+    if [ $? -ne 0 ]; then # $? retrieves the exit code of the last command
+        echo "Error in $file!"
+        exit 1
+    else
+        echo -e "Succeed!\n"
     fi
 done
 
